openapi: 3.2.0
info:
  title: KnightFrank Api v3 Search API
  description: KnightFrank Api v3
  version: v1
tags:
- name: Search
paths:
  /search:
    get:
      tags:
      - Search
      parameters:
      - name: term
        in: query
        schema:
          type: string
      - name: isoCode
        in: query
        schema:
          type: string
      - name: domain
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
